site_name: "Юлия Каримова — DevOps & Python"
site_description: "Проектирование и развертывание веб-решений в эко-системе Python"
site_author: "Yuliya karimova"

theme:
  name: null
  custom_dir: theme
  language: ru
  features:
    - navigation.top

use_directory_urls: true

markdown_extensions:
  - toc:
      permalink: false
      toc_depth: 2

extra_css:
  - assets/css/main.css
extra_javascript:
  - assets/js/main.js

extra:
  git_repo: https://github.com/yuliya-karimova/python-itmo

nav:
  - Обо мне: index.md
  - Отчет: report.md
  - Исследование: research.md